### ISSUE TITLE
error while syncing probably related to form definition downloads

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#119]
the error log is as posted below
Caused by: java.lang.NullPointerException
            at org.ei.opensrp.service.AllFormVersionSyncService.pullFormDefinitionFromServer(AllFormVersionSyncService.java:79)
            at org.ei.opensrp.sync.UpdateActionsTask$1.actionToDoInBackgroundThread(UpdateActionsTask.java:47)
            at org.ei.opensrp.sync.UpdateActionsTask$1.actionToDoInBackgroundThread(UpdateActionsTask.java:41)
            at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:28)
            at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)

**Comment by raihan-mpower** [comment]
@dimasciput are you facing similar error in your on field deployments?

**Comment by raihan-mpower** [comment]
fixed it in latest release. will reopen if problem persists regarding form download consistency. Currently placed a try -catch block to handle null in case of poor connectivity or failed form version check which was causing the error
