### ISSUE TITLE
form update check from server causing application to crash

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#120]
Caused by: java.lang.NullPointerException
            at org.ei.opensrp.service.AllFormVersionSyncService.pullFormDefinitionFromServer(AllFormVersionSyncService.java:79)
            at org.ei.opensrp.sync.UpdateActionsTask$1.actionToDoInBackgroundThread(UpdateActionsTask.java:47)
            at org.ei.opensrp.sync.UpdateActionsTask$1.actionToDoInBackgroundThread(UpdateActionsTask.java:41)
            at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:28)
            at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:18)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
The error log from the crash
This is causing the app to crash a lot whenever it is connected to the internet.
This is related to the form definition checking and probably is getting null from either server or client.
Also I have previously mentioned some fixing is required in the form definition download checking as well check #108 .

**Comment by raihan-mpower** [comment]
@dimasciput and @koros have you guys faced similar issues? Can this be something related to our server?

**Comment by ahmedihs** [comment]
@raihan-mpower  i think . i have encountered the same problem whenever form_definition version is lower than in android , this occurs .

**Comment by raihan-mpower** [comment]
fixed this ...needs checking

**Comment by koros** [comment]
@raihan-mpower please confirm whether the issue is now fixed
