### ISSUE TITLE
Null pointer in the Repository class causes the App to crash 

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#134]
@dimasciput as per the crashylitics report the exception that is responsible for highest number of app crashes occurs while trying to access the database path in the Repository class see (https://www.fabric.io/dimas-tri-ciputras-projects/android/apps/org.ei.opensrp.indonesia/issues/56543573f5d3a7f76bd33071)

# Stacktrace

Fatal Exception: java.lang.RuntimeException: Unable to start receiver org.ei.opensrp.indonesia.view.receiver.SyncBidanBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2680)
       at android.app.ActivityThread.access$1700(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
       at org.ei.opensrp.repository.Repository.<init>(Repository.java:22)
       at org.ei.opensrp.indonesia.Context.initRepository(Context.java:119)
       at org.ei.opensrp.Context.allSettings(Context.java:515)
       at org.ei.opensrp.Context.httpAgent(Context.java:467)
       at org.ei.opensrp.indonesia.Context.uniqueIdService(Context.java:228)
       at org.ei.opensrp.indonesia.view.receiver.SyncBidanBroadcastReceiver.onReceive(SyncBidanBroadcastReceiver.java:27)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2673)
       at android.app.ActivityThread.access$1700(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by koros** [comment]
@dimasciput @raihan-mpower what happens if an exception is encountered while initializing the the Repository class but suppressed, should we suppress the exception or should we let the app blow, 

Iam referring to the code below, if we put a try catch block for example then a mishap happens while initializing the Repository. if we suppress that will the app logic still be sound?.

```java
public Repository(Context context, Session session, DrishtiRepository... repositories) {
        super(context, session.repositoryName(), null, 1);
        this.repositories = repositories;
        this.databasePath = context.getDatabasePath(session.repositoryName());
        this.context = context;
        this.dbName = session.repositoryName();
        this.session = session;

        SQLiteDatabase.loadLibs(context);
        for (DrishtiRepository repository : repositories) {
            repository.updateMasterRepository(this);
        }
    }

```

**Comment by koros** [comment]
@dimasciput see also https://github.com/OpenSRP/opensrp-client/blob/opensrp-indonesia-faster-forms/opensrp-app/src/main/java/org/ei/opensrp/Context.java#L473, is it suposed to return null?

**Comment by dimasciput** [comment]
@koros it was initiated in Indonesia context class -> https://github.com/OpenSRP/opensrp-client/blob/opensrp-indonesia-faster-forms/opensrp-indonesia/src/main/java/org/ei/opensrp/indonesia/Context.java

**Comment by dimasciput** [comment]
@koros : rather than using try-catch, should we just do null checking for the context ?

**Comment by koros** [comment]
Ok i see, cool just verify whether its responsible for the null pointer issues

**Comment by koros** [comment]
@dimasciput alright, yeah we can do null check but what if another exception is thrown in the inner classes/functions it means there is a chance still of the app crashing, or what do you think,  that function has at least 5 lines of code that can potentially throw and exception unless we also go inside each functioning make sure its not accessing a null reference

**Comment by dimasciput** [comment]
@koros I guess I know what the issue is. I'll help to fix it tomorrow.

**Comment by koros** [comment]
@dimasciput alright cool, Thanks

**Comment by koros** [comment]
@kercobo @dimasciput I have just pushed a commit for this issue, Well continue monitoring the logs from crashylitics to ascertain the fix.
