### ISSUE TITLE
Prevent the app from crashing after session expiry

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#142]
Currently the method that checks whether the session is expired https://github.com/OpenSRP/opensrp-client/blob/master/opensrp-app/src/main/java/org/ei/opensrp/view/activity/SecuredActivity.java#L48
Will try to redirect the user to login page by starting an intent org.ei.opensrp.view.activity.LoginActivity, however none of the Current country implementations is using this Activity thus resulting in an Exception

##### Indonesia apk

 Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ei.opensrp.indonesia/org.ei.opensrp.indonesia.view.activity.BidanHomeActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.ei.opensrp.indonesia/org.ei.opensrp.view.activity.LoginActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by android.content.ActivityNotFoundException: Unable to find explicit activity class {org.ei.opensrp.indonesia/org.ei.opensrp.view.activity.LoginActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1761)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
       at android.app.Activity.startActivityForResult(Activity.java:3736)
       at android.app.Activity.startActivityForResult(Activity.java:3697)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
       at android.app.Activity.startActivity(Activity.java:4007)
       at android.app.Activity.startActivity(Activity.java:3975)
       at org.ei.opensrp.view.activity.SecuredActivity.onCreate(SecuredActivity.java:50)
       at android.app.Activity.performCreate(Activity.java:5933)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by koros** [comment]
@kercobo can you reflect this changes on the Indonesian app as well

**Comment by koros** [comment]
Issue fixed @ahmedihs reflect the changes on the PK branch
