### ISSUE TITLE
Cannot sync clients imported into OpenMRS with Android App

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#487]
The error raised is:

org.ei.opensrp.path.repository.PathRepository: com.google.gson.JsonSyntaxException: 2017-03-19T21:00:00.000Z
                    at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:107)
                    at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:82)
                    at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:35)
                    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
                    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
                    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
                    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
                    at com.google.gson.Gson.fromJson(Gson.java:805)
                    at com.google.gson.Gson.fromJson(Gson.java:770)
                    at com.google.gson.Gson.fromJson(Gson.java:719)
                    at com.google.gson.Gson.fromJson(Gson.java:691)
                    at org.ei.opensrp.path.repository.PathRepository.convert(PathRepository.java:332)
                    at org.ei.opensrp.path.repository.PathRepository.batchInsertClients(PathRepository.java:284)
                    at org.ei.opensrp.path.sync.ECSyncUpdater.batchSave(ECSyncUpdater.java:179)
                    at org.ei.opensrp.path.sync.ECSyncUpdater.fetchAllClientsAndEvents(ECSyncUpdater.java:88)
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask.sync(PathUpdateActionsTask.java:142)
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask.access$000(PathUpdateActionsTask.java:44)
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask$1.actionToDoInBackgroundThread(PathUpdateActionsTask.java:83)
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask$1.actionToDoInBackgroundThread(PathUpdateActionsTask.java:80)
                    at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:30)
                    at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:20)
                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                    at java.lang.Thread.run(Thread.java:841)
                 Caused by: java.text.ParseException: Unparseable date: "2017-03-19T21:00:00.000Z" (at offset 19)
                    at java.text.DateFormat.parse(DateFormat.java:555)
                    at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:105)
                    at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:82) 
                    at com.google.gson.DefaultDateTypeAdapter.deserialize(DefaultDateTypeAdapter.java:35) 
                    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) 
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95) 
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183) 
                    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) 
                    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) 
                    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) 
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95) 
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183) 
                    at com.google.gson.Gson.fromJson(Gson.java:805) 
                    at com.google.gson.Gson.fromJson(Gson.java:770) 
                    at com.google.gson.Gson.fromJson(Gson.java:719) 
                    at com.google.gson.Gson.fromJson(Gson.java:691) 
                    at org.ei.opensrp.path.repository.PathRepository.convert(PathRepository.java:332) 
                    at org.ei.opensrp.path.repository.PathRepository.batchInsertClients(PathRepository.java:284) 
                    at org.ei.opensrp.path.sync.ECSyncUpdater.batchSave(ECSyncUpdater.java:179) 
                    at org.ei.opensrp.path.sync.ECSyncUpdater.fetchAllClientsAndEvents(ECSyncUpdater.java:88) 
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask.sync(PathUpdateActionsTask.java:142) 
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask.access$000(PathUpdateActionsTask.java:44) 
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask$1.actionToDoInBackgroundThread(PathUpdateActionsTask.java:83) 
                    at org.ei.opensrp.path.sync.PathUpdateActionsTask$1.actionToDoInBackgroundThread(PathUpdateActionsTask.java:80) 
                    at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:30) 
                    at org.ei.opensrp.view.LockingBackgroundTask$1.doInBackground(LockingBackgroundTask.java:20) 
                    at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                    at java.lang.Thread.run(Thread.java:841) 
```

**Comment by geoffreymuchai** [comment]
closed by #3b2ea7d
