### ISSUE TITLE
App crash on clicking on child's dob - birth registration form

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#488]
App crashes on clicking child's dob field in the birth registration form. How to reproduce issue:
-Open birth registration form, click on the child's dob form field
-Test Device OS version:  Android 7.0
-Exception 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
                                                       at com.vijay.jsonwizard.utils.DatePickerUtils.themeDatePicker(DatePickerUtils.java:43)
                                                       at com.vijay.jsonwizard.utils.DatePickerUtils.themeDatePicker(DatePickerUtils.java:24)
                                                       at com.vijay.jsonwizard.widgets.DatePickerFactory.showDatePickerDialog(DatePickerFactory.java:349)
                                                       at com.vijay.jsonwizard.widgets.DatePickerFactory.access$100(DatePickerFactory.java:47)
                                                       at com.vijay.jsonwizard.widgets.DatePickerFactory$5.onFocusChange(DatePickerFactory.java:215)
                                                       at com.vijay.jsonwizard.customviews.GenericTextWatcher.onFocusChange(GenericTextWatcher.java:85)

**Comment by jasonrogena** [comment]
This issue occurs when we try to display dates as 'dd-mm-yyyy' devices that don't have a standard date picker dialog
